version: '3'

services:
  postgres:
    restart: always
    image: postgres
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
     - 5100:5432
    networks:
      - feedback-net
  
  redis:
    restart: always
    image: redis
    env_file:
      - .env
    networks:
      - feedback-net
    volumes:
      - redis-data:/data

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - feedback-net
  
  flask:
    build: .
    command: gunicorn -b :5000 --access-logfile - --error-logfile - feedback:app
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - feedback-net
    env_file:
      - .env


volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  es-data:
    driver: local


networks:
  feedback-net:
    driver: bridge
