"""empty message

Revision ID: d1d55e6aa483
Revises: 
Create Date: 2018-12-16 17:02:19.604904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d55e6aa483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=254), nullable=False),
    sa.Column('shop', sa.String(length=254), nullable=False),
    sa.Column('purchase', sa.String(length=254), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_purchase'), 'review', ['purchase'], unique=True)
    op.create_index(op.f('ix_review_score'), 'review', ['score'], unique=False)
    op.create_index(op.f('ix_review_shop'), 'review', ['shop'], unique=False)
    op.create_index(op.f('ix_review_user'), 'review', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_user'), table_name='review')
    op.drop_index(op.f('ix_review_shop'), table_name='review')
    op.drop_index(op.f('ix_review_score'), table_name='review')
    op.drop_index(op.f('ix_review_purchase'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
